cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'gist'
brew 'git-flow-avh'
brew 'go'
brew 'httpie'
brew 'irssi'
brew 'jq'
brew 'macvim', args: ['HEAD', 'with-lua', 'with-luajit', 'with-override-system-vim']
brew 'mariadb'
brew 'node'
brew 'openssl'
brew 'rabbitmq'
brew 'redis'
brew 'terminal-notifier'
brew 'zsh'

cask 'bartender'
cask 'caffeine'
cask 'datagrip'
cask 'gitter'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'java'
cask 'jing'
cask 'kaleidoscope'
cask 'parallels-desktop'
cask 'postman'
cask 'spectacle'
cask 'spotify'
cask 'popkey'

mas 'microsoft-remote-desktop', id: 715768417
