cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'ack'
brew 'bash-completion'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'gist'
brew 'git'
brew 'git-flow-avh'
brew 'htop'
brew 'macvim', args: ['HEAD', 'with-lua', 'with-luajit', 'with-override-system-vim']
brew 'mysql'
brew 'nmap'
brew 'node'
brew 'openssl'
brew 'redis'
brew 'terminal-notifier'
brew 'python3'
brew 'postgresql@10'
brew 'terraform'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'watch'

cask 'atom'
cask 'caffeine'
cask 'flux'
cask 'gitter'
cask 'iterm2'
cask 'postman'
cask 'slack'
cask 'spotify'

