cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'ack'
brew 'bash-completion'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'gist'
brew 'git'
brew 'git-flow-avh'
brew 'htop'
brew 'jq'
brew 'macvim', args: ['HEAD', 'with-lua', 'with-luajit', 'with-override-system-vim']
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'redis'
brew 'terminal-notifier'
brew 'wget'
brew 'yarn'
brew 'zsh'

cask 'lastpass'
cask 'atom'
cask 'caffeine'
cask 'flux'
cask 'gitter'
cask 'hipchat'
cask 'iterm2'
cask 'jing'
cask 'kap'
cask 'parallels-desktop'
cask 'postman'
cask 'skype-for-business'
cask 'slack'
cask 'spectacle'
cask 'spotify'

mas 'microsoft-remote-desktop', id: 715768417
mas 'onedrive', id: 823766827
